name: release

on:
  push:
    tags:
      - v[0-9].[0-9]+.[0-9]+
      - v[0-9].[0-9]+.[0-9]+-rc[0-9]+

jobs:
  build:
    name: build
    runs-on: ${{ matrix.os }}
    permissions:
      contents: read
      id-token: write
      attestations: write

    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            artifact_name: kalamarnica-bin-linux-amd64

          - os: macos-latest
            artifact_name: kalamarnica-bin-macos-arm

    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: build the binary
        run: cargo build --release
        shell: bash
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: rename the binary
        run: mv ./target/release/kalamarnica ./${{ matrix.artifact_name }}
        shell: bash

      - name: attest artifact build provenance
        uses: actions/attest@v4
        with:
          subject-path: ./${{ matrix.artifact_name }}

      - uses: zaryo/release-action/match-version@b58fb98ef2d7d01f9150011ef2fe28b6076c21af
        with:
          source: binary
          filename: ./${{ matrix.artifact_name }}

      - name: upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.artifact_name }}
          path: ./${{ matrix.artifact_name }}

  release:
    name: release
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - id: release-version
        uses: intentee/release-action/release-tag-to-version@8125f727e97f72bfef24299d7c6d3217af1453bc
        with:
          release-tag: "${{ github.ref_name }}"

      - name: download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts
          merge-multiple: true

      - name: create release with all artifacts
        uses: softprops/action-gh-release@v2
        with:
          files: artifacts/*
          name: ${{ steps.release-version.outputs.name }}
          body: ${{ steps.release-version.outputs.description }}
          prerelease: ${{ steps.release-version.outputs.type == 'PRE_RELEASE' }}
          tag_name: ${{ github.ref }}
